version: "3"

services:
  app1:
    image: crud
    ports:
      - "8080:8080"
  postgres:
    container_name: parking
    image: postgres
    environment:
      POSTGRES_DB: "egormelnikovdb"
      POSTGRES_USER: "egormelnikov"
      POSTGRES_PASSWORD: "54236305"
    ports:
      - "5444:5432"